/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ahorcado;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author lipsky
 */
public class PanelAhorcado extends javax.swing.JPanel {

    private int errores = 0;

    public PanelAhorcado() {
        setPreferredSize(new Dimension(300, 400));
        setBackground(Color.WHITE);
        setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));
    }

    public void setErrores(int errores) {
        this.errores = errores;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setStroke(new BasicStroke(4));

        // Dibujo de la estructura (Horca)
        g2.setColor(new Color(101, 67, 33)); // Marrón
        g2.drawLine(50, 350, 250, 350); // Base
        g2.drawLine(100, 350, 100, 50);  // Poste
        g2.drawLine(100, 50, 200, 50);   // Travesaño superior

        g2.setColor(Color.BLACK);
        // Lógica de dibujo según el orden solicitado
        if (errores >= 1) {
            g2.drawOval(175, 70, 50, 50);       // Cabeza
        }
        if (errores >= 2) {
            g2.drawLine(200, 120, 200, 220);    // Torso
        }
        if (errores >= 3) {
            g2.drawLine(200, 140, 240, 180);    // Brazo derecho 💪
        }
        if (errores >= 4) {
            g2.drawLine(200, 140, 160, 180);    // Brazo izquierdo 💪
        }
        if (errores >= 5) {
            g2.drawLine(200, 220, 230, 280);    // Pierna derecha 🦵
        }
        if (errores >= 6) {
            g2.drawLine(200, 220, 170, 280);    // Pierna izquierda 🦵
        }
        if (errores >= 7) {
            g2.setColor(Color.RED);
            g2.drawLine(200, 50, 200, 70); // Cuerda final
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
